### ISSUE TITLE
Request: Add an option to upgrade blocks of a claimed POI

### ISSUE THREAD

**Issue by Ghostwalker71** [OCB7D2D/OcbClaimAutoRepair#7]
Hi, I left a message on your nexus page but figured here would probably be more noticed.
I would like an option to upgrade undamaged blocks. So that once they have been repaired they then auto upgrade while keeping their texture sets.
This would need to be processed from the lowest block first as upgrading the top blocks first would collapse the structure. A menu to choose which type of blocks would be auto upgraded would also be superb.

Also If you set your code to read the blocks within the range of the claim block and output the block list to a json file you could reduce the cpu load. Then process the blocks listed in the json file and delete them as they are repaired/upgraded. you would only need to rescan after combat or a set time had passed.

**Comment by mgreter** [comment]
Sorry, but that is not really possible/feasible for various reason.
E.g. blocks may change at any time by any other player, zed entity or even TileEntity.
So using a cache doesn't really work (you'd want that in-memory and not on disk anyway).
Another one is the UI part, which I don't want to add due to compatibility issues with UI mods.
